#!/bin/sh

for zt in $(uci -q show firewall|grep "network='zt") ; do
zt=$(uci -q get ${zt//=*}) ; [ -d /sys/class/net/$zt ] || {
uci -q batch <<-EOF >/dev/null
del network.$zt
commit network
delete firewall.$zt
del $(uci -q show firewall | sed -n -e "/\.src='$zt'$/s///p" | sed -n -e "1p")
commit firewall
EOF
ifup $INTERFACE ; }
done
